### ISSUE TITLE
Trino Gateway Health check fails when trino cluster has oauth2 enabled

### ISSUE THREAD

**Issue by JustinR5** [trinodb/trino-gateway#166]
Whenever Trino gateway runs a health check with the trino backend clusters, it returns an 'Unauthorized to fetch cluster stats' error and sets the status of the cluster to 'false'. When changing trino authentication to 'form' from 'oauth2' the health check works.

**Comment by willmostly** [comment]
Trino only currently supports the authorization code flow, so you'll need to set up a separate authn mechanism for the gateway service user. 

For example, you can set `http-server-authorization.types = OAUTH2, PASSWORD` and set up the password database with a service user for the Gateway. The gateway only needs access to the `system.runtime` schema for health checks so you can restrict its access to everything else.

**Comment by andythsu** [comment]
if the auth `oauth2` then useApi has to be set to false, since oauth2 doesn't support `/ui/api/stats`

**Comment by mosabua** [comment]
TLS is not required for JDBC connections

**Comment by oneonestar** [comment]
Please reopen if things still doesn't work for you.
