### ISSUE TITLE
Refactor LogFilterFactory

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#195]
To get rid of usage of `ch.qos.logback.classic.spi.ILoggingEvent`;

That would allow us to get rid of the dependency  `ch.qos.logback:logback-classic:jar:1.4.8:compile`

Part of #184

**Comment by andythsu** [comment]
I think logback is the framework used by dropwizard and LogFilterFactory is used to filter out messages that contain "Authorization" keyword. Do we want to get rid of filters in general? Or switch to another framework

**Comment by mosabua** [comment]
@andythsu .. logback is fine. What we want to get rid of is the old logback-classic usage .. there is only one class that uses it and it pull in the old jar. I assume there is a modern replacemnt in the normal logback and then we can get rid of that jar as dependency.

**Comment by andythsu** [comment]
I see. I can give it a try. You can assign it to me

**Comment by mosabua** [comment]
Decided to fix dependency declaration instead. @andythsu will send PR.
