### ISSUE TITLE
Replace ActiveJDBC with JDBI

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino-gateway#229]
The example PR is https://github.com/trinodb/trino-gateway/pull/145

- [x] query_history #145
- [ ] selectors https://github.com/trinodb/trino-gateway/pull/284
- [x] exact_match_source_selectors https://github.com/trinodb/trino-gateway/pull/285
- [x] gateway_backend #231
- [ ] resource_groups
- [x] resource_groups_global_properties #230

**Comment by mosabua** [comment]
Thanks for filing this issue. It will help with tracking and also potentially others helping out.
