### ISSUE TITLE
MySQL driver does not support TLS 1.2

### ISSUE THREAD

**Issue by willmostly** [trinodb/trino-gateway#24]
The MySQL driver requires enabling TLS1 and/or 1.1 in the JDK, or setting `SSLMode=Disabled`.

**Comment by mosabua** [comment]
We should probably look at updating the driver as well .. I doubt it is up to date..

**Comment by oneonestar** [comment]
Already updated to a relatively new version (`mysql-connector-j:8.3.0`).
Shouldn't have issue with TLS 1.2.
https://github.com/trinodb/trino-gateway/blob/2e88df2d19598db49618d1764d49cef6574fdf83/gateway-ha/pom.xml#L27
