### ISSUE TITLE
Fail to verify with test code

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#28]
[This recent PR](https://github.com/trinodb/trino-gateway/pull/18) causes `verify` command to fail because `maven-surefire-plugin` was removed.
Is there a way to add jvm ops for tests? 

I noticed that `-DargLine` is a way to add ops when using mvn cmd
- `mvn clean verify -DargLine="$(tr -s '\r\n' ' ' < ".mvn/jvm.config")"` works for [ci](https://github.com/trinodb/trino-gateway/blob/main/.github/workflows/ci.yml#L32)
- https://stackoverflow.com/a/24892321

## error log for main branch

https://github.com/trinodb/trino-gateway/actions/runs/6086764118/job/16513838158

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2c4d0347

**Comment by mosabua** [comment]
https://github.com/trinodb/trino-gateway/pull/30
