### ISSUE TITLE
After the cluster outage was resolved, the restored cluster did not appear in the list of available nodes

### ISSUE THREAD

**Issue by MadlifeZhou** [trinodb/trino-gateway#324]
I added two clusters, Trino A and Trino B. At that time, Trino B cluster experienced an outage. When accessing the API at `gateway/backend/active`, it returned Trino A cluster. After the Trino B cluster was restarted and recovered, accessing the same API `gateway/backend/active` still only returned the Trino A cluster. Additionally, when connecting to the gateway through the Trino client, request could not reach the Trino B cluster.

**Comment by oneonestar** [comment]
The default health check period is 60 seconds. You can try a shorter period using the following config:
https://trinodb.github.io/trino-gateway/operation/?h=taskdelayseconds#query-routing-options
```
monitor:
  taskDelaySeconds: 10
```
