### ISSUE TITLE
The UI errors out with "The network has wandered off, please try again later!"

### ISSUE THREAD

**Issue by vishalya** [trinodb/trino-gateway#330]
Login to the new gateway web UI using OAuth2/ODIC. Let it go inactive for about 10 min.
Now interact with UI by clicking on the menu - Dashboard or Cluster on the left side.
Observe that the UI show an error message - The network has wandered off, please try again later!

Workaround:
Logout and log back in

**Comment by mosabua** [comment]
Maybe we should have an automatic logout when user is inactive ..

**Comment by vishalya** [comment]
Yes, that would work.
