### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino-gateway#34]
The link in https://github.com/trinodb/trino-gateway/blob/main/docs/development.md#contributing return 404. 

<img width="531" alt="Screenshot 2023-09-12 at 14 18 14" src="https://github.com/trinodb/trino-gateway/assets/6237050/0a674dd0-b3eb-45cd-acd0-837c4d39e0a5">

**Comment by mosabua** [comment]
Thanks for reporting .. the whole docs still need a review and update. We have barely started. In this case we have to think about where we link to ... maybe the Trino site itself and update stuff there.
