### ISSUE TITLE
Query distribution graph time is in UTC

### ISSUE THREAD

**Issue by vishalya** [trinodb/trino-gateway#369]
Go to the dashboard, observe that the chart time is UTC and not in the local time. The time axis should be in local user time zone.

**Comment by Chaho12** [comment]
Hmm that is wierd. on ours it is in local time (its 07:26 am)
![image](https://github.com/trinodb/trino-gateway/assets/25147023/367b0a04-2de6-46f1-9f11-02549ba6b33f)

**Comment by ytwp** [comment]
Currently, it is using the server time zone, it should use the client time zone.🧐

**Comment by Chaho12** [comment]
Ah i see. Would you like to make a fix @ytwp ?

**Comment by ytwp** [comment]
> Ah i see. Would you like to make a fix @ytwp ?

Yeah, I will fix it
