### ISSUE TITLE
Call for logo suggestions

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#38]
Maybe do a competition by submitting a logo as comment here.

**Comment by alaturqua** [comment]
Here are some examples generated by DALL-E 3 :)
![logo4](https://github.com/trinodb/trino-gateway/assets/17232317/2989196a-ccb2-45fc-bab1-d55c47347d0d)
![logo5](https://github.com/trinodb/trino-gateway/assets/17232317/4c0d3b9f-cb31-4aa3-9ece-f4890b78dc6f)
![logo6](https://github.com/trinodb/trino-gateway/assets/17232317/b8e24296-6825-4a70-ab46-b61a8b49a899)
![logo1](https://github.com/trinodb/trino-gateway/assets/17232317/7f660882-9a7e-44b5-9f6c-4822f436da92)
![logo3](https://github.com/trinodb/trino-gateway/assets/17232317/8b908d08-bd10-4429-95d0-13042003c642)
![logo2](https://github.com/trinodb/trino-gateway/assets/17232317/ce96b289-d95b-45ad-bd62-2a38298a307e)

**Comment by mosabua** [comment]
Hahaha @alaturqua .. those are all way to detailed. We will get some going with a similar look and feel as the Trino logo itself. We currently have a temporary solution in place
