### ISSUE TITLE
Open API spec for Gateway APIs

### ISSUE THREAD

**Issue by Nexengineer** [trinodb/trino-gateway#380]
Hi,

Do we have any OpenAPI spec for gateway apis.

**Comment by mosabua** [comment]
Not at this stage but that might be useful in the longer run. What is the use case you are trying to work on

**Comment by oneonestar** [comment]
Good to add when we reorganize the endpoints (see https://github.com/trinodb/trino-gateway/wiki/Contributor-meetings#trino-gateway-dev-sync-29-may-2024).

**Comment by Nexengineer** [comment]
@mosabua  I am trying to make  application which will handle auth of gateway api using OAUTH2.

**Comment by Nexengineer** [comment]
Closing this
