### ISSUE TITLE
Helm chart not available on any chart repository

### ISSUE THREAD

**Issue by silent-lad** [trinodb/trino-gateway#391]
Is there a conscious decision to not push the gateway chart to trino helm repository? The only way to use it now is to clone the repo and copy paste the helm chart folder in your IAAC repo

**Comment by nineinchnick** [comment]
The chart is published to github pages, which you can add as a repository. This is described in the Readme.

**Comment by mosabua** [comment]
Not really. We are not pushing the Trino helm chart either .. but we might end up pushing both. Currently the Trino Gateway one is still very early in terms of quality.

**Comment by nineinchnick** [comment]
Trino Helm chart is published to GitHub pages, which can be added as a repo in Helm. The same could be done here, but I think we should avoid having two separate Helm repos. I can check if we can include the gateway chart in the main Trino repo.

**Comment by mosabua** [comment]
Ok... we have to figure out how this works since in this repo we use github pages to host the website and I was hoping we can do the same for the charts. Can github pages host both?

**Comment by Nikhil-Madhavarapu** [comment]
Guys, any update on chart repository?
I have a requirement to pull the charts as dependency from helm chart.

**Comment by mosabua** [comment]
After our discussion in the dev sync today I am assigning this to @nineinchnick  .. @willmostly and @mosabua and others will help

**Comment by nineinchnick** [comment]
I had to copy the chart into the charts repo anyway, PTAL: https://github.com/trinodb/charts/pull/253

**Comment by nineinchnick** [comment]
It's done
