### ISSUE TITLE
Query History incorrectly treats source as a required field

### ISSUE THREAD

**Issue by willmostly** [trinodb/trino-gateway#392]
`QueryHistory` assumes that `source` is [never null](https://github.com/trinodb/trino-gateway/blob/7b694701cf22a8de6a6771de59b51290b5f584dc/gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java#L34), however clients are not required to set `X-Trino-Source`. This prevents lookup for such queries in a multi instance deployment, and prevents the Query History page from working if any rows returned for a search have `source = NULL`.

**Comment by oneonestar** [comment]
Fixed by #381
