### ISSUE TITLE
Pass object instead of multiple strings to routingManager?

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#394]
RoutingManager's provideBackendForRoutingGroup or provideAdhocBackend functions are called in [QueryIdCachingProxyHandler.java](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java#L332-L341) but within the function, it sends only routing group (if there is a header named "X-Trino-Routing-Group") and user info.

But in request headers, there are much more helpful informations, such as source, catalog, clientTags etc.
![image](https://github.com/trinodb/trino-gateway/assets/25147023/6f3365d2-479c-40b1-8ab2-072058b02962)

So, how about passing an object which includes all headers?

**Comment by mosabua** [comment]
I think thats a good idea .. there might also be more headers in the future so its a bit easier to extend.

**Comment by oneonestar** [comment]
Make sense. We need to choose a data structure for the headers, eg.
* `Map<String, List<String>>`
* `ListMultimap<String, String>`
* `MultivaluedMap<String, String>`

**Comment by Chaho12** [comment]
I think `MultivaluedMap<String, String>` sounds good as trino uses it at multiple cases, [case1](https://github.com/trinodb/trino/blob/89328441556474f5a69b7259dd7b4aa0a83a3da4/core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java#L176-L194), [case2](https://github.com/trinodb/trino/blob/89328441556474f5a69b7259dd7b4aa0a83a3da4/core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticator.java#L109-L123)

**Comment by willmostly** [comment]
>  it sends only routing group (if there is a header named "X-Trino-Routing-Group") 
if you use `RuleReloadingRoutingGroupSelector`, the routing group as determined by the routing rules will be passed.

**Comment by willmostly** [comment]
https://github.com/trinodb/trino-gateway/pull/398#pullrequestreview-2156954353
