### ISSUE TITLE
Adopt airlift as base framework

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#41]
Currently the project uses an old version of Dropwizard. Airlift is a superior alternative that is actively maintained and also used in Trino itself. 

Rather than upgrading Dropwizard it might be better to move to Airlift and then take advantage of aspects such as easy tarball creation, config system, opentelemety support and much more. This is the preferred approach by @martint. 

Potential an initial upgrade of dropwizard to fix the worst issues might still be a good step.

**Comment by mosabua** [comment]
This is done and part of version 5 onwards

**Comment by mosabua** [comment]
Partially using airlift already .. but not as full base framework

**Comment by oneonestar** [comment]
Preparation phase (splittable):
- [ ] Remove dropwizard.auth: #289 
- [ ] Remove dropwizard.configuration
- [ ] (Maybe) Refactor module injection

Migration phase (all-at-once):
- [ ] Remove dropwizard.*
- [ ] Update to Jetty 12.0.7 EE10 (Ref: https://github.com/airlift/airlift/pull/1089)
- [ ] com.codahale.metrics to opentelemetry
- [ ] Use airlift for bootstrap
- [ ] Migrate to airlift.configuration

Uncertain things:
* Configuration: .properties or .yaml
Currently Trino and Airlift are using .properties, but gateway is using YAML.
IMO, YAML is a better configuration format.
Adding support on yaml in airlift could be an option (see https://github.com/airlift/airlift/issues/738#issuecomment-508444448).
* Listen to multiple ports using Airlift
Request service at :9080, application service at :9081, and the Admin service at :9082
Not sure how to do this using Airlift.
