### ISSUE TITLE
Quickstart docker trino images lacks process-forward conf

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#422]
Related issue - https://github.com/trinodb/trino-gateway/pull/396

Since trino 451, it rejects X-Forward header.
Quickstart doc runs trino in docker but it trino server fails to process header.
```
#Start a pair of trino servers on different ports
docker run --name trino1 -d -p 8081:8080 trinodb/trino
docker run --name trino2 -d -p 8082:8080 trinodb/trino
```

**Comment by oneonestar** [comment]
Fixed by #430
