### ISSUE TITLE
trino-gateway how to skip backend tls with invalidate certificates

### ISSUE THREAD

**Issue by Alienero** [trinodb/trino-gateway#434]
When I using some backend which with invalidate certificates, trino-gateway will cannot connect to the backend. And I am not found any config can skip validation, like tirno-cli --insecure

**Comment by oneonestar** [comment]
Does this work for you?
https://trinodb.github.io/trino-gateway/security/#extra-self-signed-certificate-in-trino

**Comment by Alienero** [comment]
Thank you for the response from @oneonestar. The `-Djavax.net.ssl.trustStore` can resolve part of the issue. When using `ClusterStatsInfoApiMonitor` as the state monitor, the HTTP client will validate the hostname, and this client cannot be configured with `setVerifyHostname` in config file. In the proxy phase, this can be configured through the file `http-client.https.hostname-verification: false`. Currently, I am using it by modifying the code of `ClusterStatsInfoApiMonitor`.

**Comment by oneonestar** [comment]
Closed by #436.
