### ISSUE TITLE
lower-case headers passed on to trino gateway is not handled case insensitively

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#450]
https://trinodb.slack.com/archives/C059KUNPTSP/p1724808596538969

Changing from HttpServletRequest to (Airlift httpclient) Request causes this bug where getHeader is case now case sensitive

**Comment by Chaho12** [comment]
Cause
- HttpServletRequest -> (Airlift) Request is case sensitive so getHeader is not returning correctly
- https://github.com/airlift/airlift/pull/1257

**Comment by mosabua** [comment]
Looks like we just need a airlift release and then updated airlift and adjust any left over code.

**Comment by Chaho12** [comment]
pom updated for airlift release. 
- https://github.com/trinodb/trino-gateway/pull/457

Issue is fixed but we should migrate from HttpServletRequest to (Airlift) Request type.

**Comment by mosabua** [comment]
> Issue is fixed but we should migrate from HttpServletRequest to (Airlift) Request type.

Sure.. but that is not required for a release or for this fix, right @Chaho12 ? Should we close this ticket and do a follow up one for the refactor?

**Comment by Chaho12** [comment]
Yeah closing issue a fix is resolved
