### ISSUE TITLE
Create documentation for installation

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#50]
* How to install using the JAR 
* How to install using the Docker container
* Requirements (external DB...)
* How to start/stop..
* Minimal configuration
* Required Java and OS and more

**Comment by andythsu** [comment]
There's some doc in development section already. Maybe we can just add onto it

**Comment by mosabua** [comment]
I feel like we need a separate page .. or even more. Over time we will have instructions jar, tarball, docker, helm, and the related infrastructure.. and ultimately the person installing and running Trino Gateway might not be a developer...

**Comment by andythsu** [comment]
Just curious who else could be installing and running Trino Gateway if they are not developer? I agree to have as many docs as possible, but at the same time it feels like a duplicate of development doc, or somewhat similar.

**Comment by mosabua** [comment]
Well.. whoever is on the operations team for multiple Trino clusters and the related infrastructure .. they could be a sysadmin that has no Java knowledge.. or a k8s expert or whatever. yes.. in most cases they will have some development background .. but essentially the needs are different .. e.g. they wont have to worry about installing Maven .. and when using helm or docker also not about installing Java..

**Comment by pulkitkalia1994** [comment]
I would love to have Installation guide and docker support for Trino gateway.

**Comment by mosabua** [comment]
Current docs are suitable to get started. Further work are incremental improvements.

https://github.com/trinodb/trino-gateway/blob/main/docs/installation.md
