### ISSUE TITLE
Parsing fails when there isn't default schema

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#528]
I notice there is error on parsing TrinoQueryProperties file, when there isn’t default schema set while using WITH clause
sql is sth like this where it has default catalog, but not default schema for temporary table created with WITH.

```SQL
WITH ctr AS (
  SELECT sscode,
         SUM(sc) AS sc,
  FROM mysql_laim_data.lboard_data.ctr
  WHERE ...
), t_summary_by_sscode AS (
SELECT ...
FROM
(
  SELECT *
  FROM ctr LEFT OUTER JOIN ctr_before_one
  USING (sscode)
  ) LEFT OUTER JOIN ctr_before_two
  USING (sscode)
)

SELECT sscode,
       QC
FROM t_summary_by_sscode
...
```

![Image](https://github.com/user-attachments/assets/2921b275-0148-4a68-8524-08208b0c812a)
![Image](https://github.com/user-attachments/assets/ce1b0da8-019d-48fb-8cc0-4fe5fbc79f17)

**Comment by Chaho12** [comment]
Yes so if schema is empty, current code would throw `unsetDefaultExceptionSupplier` because default schema is empty.
Throwing error is not what we expect as SQL is valid
- `case 1 -> QualifiedName.of(defaultCatalog.orElseThrow(this::unsetDefaultExceptionSupplier), defaultSchema.orElseThrow(this::unsetDefaultExceptionSupplier), tableParts.getFirst())`
- https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java#L389

**Comment by Chaho12** [comment]
I am thinking sth like this where we have a set that has list of temporary tables that is created when parsing to a tree.

```java
private QualifiedName qualifyName(QualifiedName table)
            throws RequestParsingException
{
    List<String> tableParts = table.getParts();
    return switch (tableParts.size()) {
        case 1 -> {
            String tableName = tableParts.getFirst();
            if (temporaryTables.contains(tableName)) {
                // For temporary tables, use only the table name
                yield QualifiedName.of(tableName);
            } else {
                // For non-temporary tables, use default catalog and schema if available
                yield QualifiedName.of(
                    defaultCatalog.orElseThrow(this::unsetDefaultExceptionSupplier),
                    defaultSchema.orElse(""), // Use empty string if default schema is not set
                    tableName
                );
            }
        }
        case 2 -> QualifiedName.of(defaultCatalog.orElseThrow(this::unsetDefaultExceptionSupplier), tableParts.getFirst(), tableParts.get(1));
        case 3 -> QualifiedName.of(tableParts.getFirst(), tableParts.get(1), tableParts.get(2));
        default -> throw new RequestParsingException("Unexpected table name: " + table.getParts());
    };
}
```

**Comment by mosabua** [comment]
Have not look at your code but yes .. query parsing should work with 

* empty default catalog and empty default schema
* values in both

If that is not the case, thats a bug and you should send a PR to fix that for sure.

I am not so certain if behavior is defined in Trino for

* default catalog but no schema
* default schema but no catalog

so we should find out. It might be related to the USE comment where you have to specify both.

**Comment by mosabua** [comment]
Also note .. in the CLI you can either specify catalog and schema, or just catalog, but no just schema.
