### ISSUE TITLE
MySQL 8.x support

### ISSUE THREAD

**Issue by Chaho12** [trinodb/trino-gateway#54]
Changing version to MySQL 8.x has causes issue with index size in [exact_match_source_selectors](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/resources/gateway-ha-persistence.sql#L67-L77) table's unique index, as it is innodb with utf8mb4 (4 bytes)

[trinodb/trino](https://github.com/trinodb/trino/blob/master/plugin/trino-resource-group-managers/src/main/resources/db/migration/mysql/V4__add_exact_match_source_selectors.sql#L8) solves this issue by giving limits to each unique key index UNIQUE (source(128), environment, query_type(128), resource_group_id) 

However, in gateway there is syntax issue when activejdbc executes sql.
- https://github.com/trinodb/trino-gateway/pull/53#discussion_r1334527435

**Comment by mosabua** [comment]
We should probably update the JDBC driver soon as well.. but thats a separate issue
