### ISSUE TITLE
Flaky DbResourceGroups tests

### ISSUE THREAD

**Issue by willmostly** [trinodb/trino-gateway#70]
The `TestSpecificDbResourceGroupsManager ` tests intermittently fail their assertions on the number of resource groups. This appears to potentially be a timing bug due to interaction between `TestSpecificDbResourceGroupsManager ` and `TestResourceGroupsManager`.

**Comment by mosabua** [comment]
Might be good now .. lets keep an eye on it though

**Comment by mosabua** [comment]
I think we are good with this now - at least I have not seen it be a problem anymore. Can we close @willmostly ?

**Comment by mosabua** [comment]
This seems to be gone now.
