### ISSUE TITLE
[Feature] Support for AWS Athena

### ISSUE THREAD

**Issue by jpohanka** [trinodb/trino-gateway#83]
The latest version of Athena's query engine has incorporated many features of Trino: https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-athena-announces-upgraded-query-engine/

It would be great if the Trino Gateway would support redirection to AWS Athena as well.

Offloading queries to Athena could mitigate overloading of the Trino cluster(s) in case of very high usage.

**Comment by mosabua** [comment]
I will try to answer this in more detail by updating our documentation later this week. In a nutshell .. technically this potentially impossible for aspects such as unknown Trino version in Athena and completely different client protocol. However there are aspects that might work with Athena but also other SaaS solutions and hosted versions of Trino such as Starburst Galaxy, Azure HDInsights on AKS, Google Dataproc with Trino and many others..  

As a project however our focus is very much on supporting Trino and its client protocol and API .. nothing much beyond at this stage.

**Comment by mosabua** [comment]
Updated docs now in https://github.com/trinodb/trino-gateway/blob/main/docs/installation.md#trino-clusters ... essentially we will not support Athena since its a completely different client protocol and tool (no clusters..)
