### ISSUE TITLE
Load balancing scheme in Trino gateway?

### ISSUE THREAD

**Issue by pulkitkalia1994** [trinodb/trino-gateway#84]
What's the load balancing scheme used by Trino gateway? And is there a way to change it?

**Comment by lambrospetrou** [comment]
By default the gateway picks a random cluster within the matched routing group. See https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java#L249 and https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingManager.java#L91

**Comment by mosabua** [comment]
@vishalya can you potentially take this on to document as part of the update for the linked PR ?

**Comment by oneonestar** [comment]
Please see https://trinodb.github.io/trino-gateway/routing-logic/#routing-based-on-cookies
