### ISSUE TITLE
security authorization issues？

### ISSUE THREAD

**Issue by andyliao0508** [trinodb/trino-gateway#85]
I use  Form/Basic authentication

following:
presetUsers:
  user1:
    password: <password>
    privileges: "lb_admin, lb_user"
  user2:
    password: <password>
    privileges: "lb_api"
    
    The authorized account and password pop up.
    Input user and password ,401 Unauthorized will always appear.

my setting sample:
authentication:
  defaultType: "form"

presetUsers:
  user1:
    password: "pass"
    privileges: "lb_admin, lb_user, lb_api"

**Comment by ebyhr** [comment]
Please feel free to ask in `#trino-gateway` Slack channel so that we can talk interactively. Let me close this issue.
