### ISSUE TITLE
Add Helm chart

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#87]
It might be useful to add a Helm chart to manage Trino Gateway deployment on k8s.

**Comment by Chaho12** [comment]
Would this chart go under trinodb/trino-gateway or under [trinodb/charts](https://github.com/trinodb/charts)? 

We can get this added [after dockerization is done](https://github.com/trinodb/trino-gateway/pull/113)

as of now, for templates yaml we are using
- `_helpers`, `configmap`, `deployment`, `hpa(autoscaler)`, `service`, `serviceaccount`

if there are additional files needed, please suggest

**Comment by mosabua** [comment]
I think we can keep it all in this repo

**Comment by mosabua** [comment]
We could also consider reviving a docker compose setup that we removed with https://github.com/trinodb/trino-gateway/pull/146/files .. if users desire that.

**Comment by mosabua** [comment]
@wccropper until someone in the community find time to work on it and sends a pull request for a separate module in this repo. Then we have to review and update and get to merge. We would love your help.

**Comment by luismacosta** [comment]
Hello,

I was installing trino-gateway in eks and have a helm chart to do it, with an initContainer  to initialize the database.
If you want to have a look I can create a PR.

**Comment by mosabua** [comment]
That would be AWESOME @luismacosta

**Comment by luismacosta** [comment]
helm chart https://github.com/trinodb/trino-gateway/pull/245

**Comment by mosabua** [comment]
Closed via https://github.com/trinodb/trino-gateway/pull/323
