### ISSUE TITLE
Incorrect query param type in /trino/selector/read/{resourceGroupId}

### ISSUE THREAD

**Issue by vaultah** [trinodb/trino-gateway#95]
`resourceGroupId` in `/trino/selector/read/{resourceGroupId}` is wrongly annotated with `@QueryParam`, when it's actually a path parameter:
```
@GET
@Path("/selector/read/{resourceGroupId}")
public Response readSelector(@QueryParam("resourceGroupId") String resourceGroupIdStr,
    ...
```

As a result, `/trino/selector/read/X` returns all selectors, and not just those in the `X` resource group.

**Comment by mosabua** [comment]
Fix is merged and will go out with next release.
